// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDxwwX5FfGsOSlal_aif-gOFbqydVX-C8',
    appId: '1:795031104358:web:70667cdacf072ffe1cb6a7',
    messagingSenderId: '795031104358',
    projectId: 'my-news-logs-app',
    authDomain: 'my-news-logs-app.firebaseapp.com',
    storageBucket: 'my-news-logs-app.appspot.com',
    measurementId: 'G-06QQ2156K1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkj7RkPwOk2oxemAkqvvxgmSi-KbRFy1A',
    appId: '1:795031104358:android:a2e3e3d4410d79dc1cb6a7',
    messagingSenderId: '795031104358',
    projectId: 'my-news-logs-app',
    storageBucket: 'my-news-logs-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhxMiFS5yTdDcTAHKMNmbDzKtpEVdvZcI',
    appId: '1:795031104358:ios:fac8f63685b063c11cb6a7',
    messagingSenderId: '795031104358',
    projectId: 'my-news-logs-app',
    storageBucket: 'my-news-logs-app.appspot.com',
    iosClientId: '795031104358-g5afec6kuqh2epfa7i19lcirri5gur3f.apps.googleusercontent.com',
    iosBundleId: 'com.example.firstProject',
  );
}
